version: '3'
services:
  db:
    container_name: db
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    ports:
      - 8080:8080